### ISSUE TITLE
cake3 Docs for PasswordableBehavior missing

### ISSUE THREAD

**Issue by TamiasSibiricus** [dereuromark/cakephp-tools#115]
You need to modify docs for this info
In CakePHP 3.x entity for passwordable model needs for modification like 

```
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * User Entity.
 */
class User extends Entity {

/**
 * Fields that can be mass assigned using newEntity() or patchEntity().
 *
 * @var array
 */
    protected $_accessible = [
        'username' => true,
        'password' => true,
        'password_new' => true,
        'password_confirm' => true,
        'password_current' => true,
        'email' => true,
        'active' => true,
    ];

}
```

Without this modification entity does not keep additional fields and data does not pass validation process in save process.
I got this error only in add user controller.

**Comment by dereuromark** [comment]
I guess this is still present in 3.x.
Ideally the behavior adds those fields to the accessible array itself.
Do you think you can make a PR with those changes?

**Comment by dereuromark** [comment]
Any update here maybe? That would be awesome.

**Comment by dereuromark** [comment]
Fixed with https://github.com/dereuromark/cakephp-tools/releases/tag/1.1.3 and some docs update now.
Thanks!
