### ISSUE TITLE
URL cache of tools plugin

### ISSUE THREAD

**Issue by Adnan0703** [dereuromark/cakephp-tools#128]
Hi, Mark.
I'm trying to use url cache of tools plugin. Have you tested it with pagination links? It seems it doesn't work with pagination links.
Here's the code I'm using:

In core.php

Cache::config('_cake_core_', array(
	'engine' => $engine,
	'prefix' => $prefix . 'cake_core_',
	'path' => CACHE . 'persistent' . DS,
	'serialize' => ($engine === 'File'),
	'duration' => $duration,
	'lock' => true
));

In bootstrap

Configure::write('UrlCache.active', true);
Configure::write('UrlCache.pageFiles', true);
Configure::write('UrlCache.verbosePrefixes', true);

In AppHelper.php

App::uses('MyHelper', 'Tools.View/Helper');

class AppHelper extends MyHelper {

}

I can write the test if you want.

**Comment by dereuromark** [comment]
Closed via https://github.com/dereuromark/cakephp-tools/pull/129
