### ISSUE TITLE
JsonableBehavior does not give decoded results when using "Containable"

### ISSUE THREAD

**Issue by LDSign** [dereuromark/cakephp-tools#131]
Hi Mark

JsonableBehavior does not decode the json string when the data is fetched through a "containable" association. Direkt finds do work as expected.

Do I miss some option or is this a limitation?

Thanks,
Frank

**Comment by dereuromark** [comment]
Are you using CakePHP2.5/2.6?
This is a limitation of the 2.x series of CakePHP where callbacks on models only work on the primary record.
This is fixed in 3.0.
So until then you need to add a quickfix-hook in your AppModel or manually invoke the transformation.

**Comment by LDSign** [comment]
Yeah, its 2.6.

Ok, thats no problem - I juut wanted to make sure this is no bad implementation on my side which causes problems later ;)

Hope to get my hands on 3.0 soon.

Thanks

**Comment by dereuromark** [comment]
;) Yeah
