### ISSUE TITLE
Logable autoRelation 

### ISSUE THREAD

**Issue by LDSign** [dereuromark/cakephp-tools#137]
Hi Mark

"autoRelation" in Logable behavior is not implemented yet, isn't it? Do you have any plans to do this? The setting exists though ;)

Thanks,
Frank

**Comment by dereuromark** [comment]
Feel free to PR it. Or to remove the setting.
I dont have plans due to time issues :)

**Comment by dereuromark** [comment]
LogableDelete is deprecated and only 2.x needs fixing if someone is filling to provide a PR.

**Comment by dereuromark** [comment]
Closing until PR is open.
