### ISSUE TITLE
Map  doesn`t appear if use '<?php' server tag

### ISSUE THREAD

**Issue by jhonnatas** [dereuromark/cakephp-tools#138]
I`m a cakephp beginner and not sure if this is a real issue... but,  map only appears if I use "<?="  instead of "<?php"

<?=	$this->GoogleMap->map($map_options); ?> //it works

<?php $this->GoogleMap->map($map_options); ?> //it doesn`t work.

I`m using cakephp 2.5.5

**Comment by dereuromark** [comment]
You forgot your "echo"
