### ISSUE TITLE
Bitmasked behavior multiple fields

### ISSUE THREAD

**Issue by bancer** [dereuromark/cakephp-tools#140]
I cound not find a way to use 2 bitmasked columns in the same table, f.ex. `status` and `tag`. It seems that Bitmasked behavior works only with one column per table.

**Comment by dereuromark** [comment]
I have never used more than one so far. I can look into it if you don't find a fix for it these days.

**Comment by bancer** [comment]
I fixed that to my needs. But I used an older version of the behavior. https://github.com/bancer/cakephp-tools

**Comment by dereuromark** [comment]
I wonder what a cleaner approach might be?
Having an array of fields as deep array?

    'fields' => [
        'foo' => [
            'mappedField' => 'myfoo',
            'bits' => ...,
            'defaultValue' => ...
        ],
        ...
    ]

etc?

**Comment by bancer** [comment]
Yes, that is cleaner indeed.

**Comment by dereuromark** [comment]
It was just never meant for tables to have more than a single (status) field for this behavior to use.
And using array now would make the need to remove the default key "status" in favor of an empty fields array.
So it would break BC, maybe we should to this for 3.x.

But then again you could always just attach the model multiple times..
Hm, I am undecided.

**Comment by dereuromark** [comment]
So for 2.x I added a note in the docs on how to apply this behavior multiple times using aliasing: https://github.com/cakephp/docs/pull/2526

**Comment by dereuromark** [comment]
PRs are welcome for 3.x.

**Comment by bancer** [comment]
It feels a bit non-intuitive to attach a behavior multiple times. We do not attach TranslateBehavior multiple times whenever we have multiple translatable columns for example.

**Comment by dereuromark** [comment]
Feel free to provide a PR here then, as well.
