### ISSUE TITLE
Change URL of API

### ISSUE THREAD

**Issue by blindner** [dereuromark/cakephp-tools#142]
Update API URL as per Post on Twitter:
https://twitter.com/worldweatheronl/status/576436226875613184

"We request all our API users to please change your request url from http://api.worldweatheronline.com  to http://api2.worldweatheronline.com "

**Comment by dereuromark** [comment]
"api2 seems to be down as well. Any update on when you'll be online again?" and "You cannot just change an endpoint out from underneath us. Apps that have an approval process cant adapt that quick!" are some twitter responses, and justified.

Is the problem resolved, does the original API url work again?
Its totally stupid of them to change an API url just for fun...

**Comment by dereuromark** [comment]
They resolved their shit :)
