### ISSUE TITLE
calculateDrivingTime() function

### ISSUE THREAD

**Issue by brandonjjon** [dereuromark/cakephp-tools#150]
Is there any plans for this? Or do you have any ideas about how I could implement this? I imagine it could work similarly to the distance() function, where it simply returns a value.

Any direction would be appreciated.

**Comment by dereuromark** [comment]
Can you be more specific what that would be?

**Comment by brandonjjon** [comment]
For example, when you type in directions in Google, it gives you the Driving Time as well. Like it takes 15 minutes to get from pointA to pointB.

**Comment by dereuromark** [comment]
Are you talking about the GoogleMaps functionality of the helper?
So far not for 2.x, and for 3.x the project is a standalone plugin.
