### ISSUE TITLE
Multiple label fields breaks uniqueness

### ISSUE THREAD

**Issue by cercos** [dereuromark/cakephp-tools#152]
Using the SluggedBehavior when setting the label option to an array of fields and unique is true the slugs aren't unique.

**Comment by dereuromark** [comment]
a) You always need to specify the exact version / branch you are using.
b) Can you be more specific regarding the test scenario? I am sure there are existing tests that work so the question is what is your setup so it doesnt? I need that to be able to reproduce and to fix it.

If you have time you can also make a PR with the fixes.
