### ISSUE TITLE
Jsonable: Error when find list

### ISSUE THREAD

**Issue by ayman-alkom** [dereuromark/cakephp-tools#153]
Hi @dereuromark , I had an error when I tried to run `list` finder on my model witch has a Jsonable Behavior, in Cakephp 3.x.
The error is in the line 100, I tried to correct it but I couldn't, it seems we have to check the finder name before format the the results.

Note: the `$row` in line 102 is just a string in my list finder case and not Entity, I hoped to make a PR 
thanks again for this awesome plugin.

**Comment by dereuromark** [comment]
Did the PR work out? You can also just copy and paste the fix here or provide a basic test case for it and I will see what I can do :)

**Comment by ayman-alkom** [comment]
In fact it didn't work, because I didn't know how to detect the finder name, for now I may disable the event manually to retrieve the list finder.

**Comment by ayman-alkom** [comment]
I tried with this for example:
```
    public function beforeFind(Event $event, Query $query)
        {
            $query->formatResults(function (ResultSetInterface $results) {
                return $results->map(function ($row) {
                    if(is_object($row)){
                        $this->decodeItems($row);
                    }

                return $row;
            });
        });
    }
```
but some warning still appear:

```
Warning (4096): Argument 1 passed to Tools\Model\Behavior\JsonableBehavior::Tools\Model\Behavior\{closure}() must implement interface Cake\Datasource\ResultSetInterface, instance of Cake\Collection\Collection given, called in C:\wamp\www\apps\rest_app\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php on line 436 and defined [ROOT\vendor\dereuromark\cakephp-tools\src\Model\Behavior\JsonableBehavior.php, line 104]

```

**Comment by dereuromark** [comment]
Why did you run a find list on it? Wouldn't you only want to have the decoding on a find all or first?
Can you please post the original code you tried to do?

**Comment by ayman-alkom** [comment]
````
//in columns controller
$statements = $this->Columns->Statements->find('list', ['limit' => 200]);
````
it works fine when I remove the jsonable Beauvoir

**Comment by dereuromark** [comment]
Please also always include the exact error message incl. the stack trace :)

**Comment by ayman-alkom** [comment]
Error: Call to a member function get() on a non-object 
File C:\wamp\www\apps\rest_app\vendor\dereuromark\cakephp-tools\src\Model\Behavior\JsonableBehavior.php
Line: 118

**Comment by ayman-alkom** [comment]
As I said the $row is not Entity, it is string of the Statements display field only

**Comment by ayman-alkom** [comment]
Note: in my case I dont want decoding of course, but the encoding is worked always

**Comment by dereuromark** [comment]
You also didnt show how you loaded the behavior. That is all part of a complete bug ticket in order to reproduce the issue.

**Comment by ayman-alkom** [comment]
```
    public function initialize(array $config)
    {
        $this->table('statements');
        $this->displayField('name');
        $this->primaryKey('id');
        $this->hasMany('Columns', [
            'foreignKey' => 'statement_id'
        ]);
        $this->belongsTo('ConnectionStrings',[
            'foreignKey' => 'connection_string_id'
        ]);
        $this->addBehavior('Tools.Jsonable',[
            'fields' => ['fields'],
            'input' => ['json'],
        ]);
    }
```

**Comment by ayman-alkom** [comment]
that is it, thanks a lot.
