### ISSUE TITLE
AuthUserHelper

### ISSUE THREAD

**Issue by PennyScripter** [dereuromark/cakephp-tools#156]
How can I install just the AuthUserHelper to use with tinyauth as a standalone. I don't need the other tools. Can you please advise what is required to code in.

**Comment by dereuromark** [comment]
Just ignore the Rest of the files.
That is all you need to do.

**Comment by PennyScripter** [comment]
So in bootstrap
```
Plugin::load('Tools');
```
In my appview
```
$this->loadHelper('Tools.AuthUser');
```
Is this a correct setup?

Now how do I call the results?
```
AuthUserHelper::_getUser()
```

**Comment by PennyScripter** [comment]
Is this a correct setup in the previous post? and how do I call the results?

**Comment by dereuromark** [comment]
You use a helper as documented: $this->AuthUser->...(), also note what is documented in the plugin: You need the component as well for the helper to work.

**Comment by PennyScripter** [comment]
I was missing in appcontroller
```$this->loadComponent('AuthUser');
```

Then I can call $this->AuthUser->(); to get the role?

**Comment by dereuromark** [comment]
yes
