### ISSUE TITLE
Improve Docs

### ISSUE THREAD

**Issue by ayman-alkom** [dereuromark/cakephp-tools#160]
Hi @dereuromark 
At first thanks a lot for your job
In second I just noticed that your docs needs some improvement in its styling, specially in the case of a lot of options.
I thought that using tables maybe helpful 
If you are agree I can do it but before that I want your opinion

this is a sample
https://github.com/ayman-alkom/cakephp-tools/blob/patch-2/docs/Behavior/Jsonable.md

**Comment by dereuromark** [comment]
Indeed a very good idea :)

**Comment by ayman-alkom** [comment]
I can start a PR if you want, in this case I found its binifits to mention these columns
- key
- type
- default value
- options
- desc

but sometimes the default value is not mentioned in the current docs, then I can leave them empty.

| Key  					| Type				| Default Value				| Desc 																|
| :------------ |:-----------:|:-------------------|:-----------------------------------|
| fields 				| array 			| array()							| Fields to convert 									|
| input 				| string 			| 'array' 						| json, array, param, list (param/list only works with specific fields) |
| output 				| array 			| json, array, param, list (param/list only works with specific fields) |

**Comment by dereuromark** [comment]
All right

**Comment by ayman-alkom** [comment]
https://github.com/dereuromark/cakephp-tools/pull/163

**Comment by dereuromark** [comment]
PR open.
