### ISSUE TITLE
WhoDidItBehavior does not work with Basic Auth

### ISSUE THREAD

**Issue by bancer** [dereuromark/cakephp-tools#161]
The following error is the result of add() action:
> SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`my_db`.`my_table`, CONSTRAINT `my_foreign_key` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)"

And SQL:
> INSERT INTO `my_db`.`my_table` (`column_one`, `column_two`, `column_three`, `column_four`, `modified`, `created`) VALUES (0, 0, 5.67, 128, '2015-11-25 09:55:55', '2015-11-25 09:55:55')

So, 'created_by' value is missing probably because WhoDidItBehavior uses sessions to get the authenticated user. Wouldn't it be better to use AuthComponent instead?

**Comment by dereuromark** [comment]
Indeed. Feel free to PR improvements
