### ISSUE TITLE
Passwordable current password not required during update with require false.

### ISSUE THREAD

**Issue by blieb** [dereuromark/cakephp-tools#177]
When I load passwordable behaviour like this:

$this->Users->addBehavior('Tools.Passwordable', ['current' => true, 'require' => false]);

Users can leave the "current password" field empty when updating password field. I expect that the current still is required when setting a new password.  

To fix this I've currently changed the line:
    $validator->allowEmpty($formFieldCurrent, !$this->_config['require']);
to:
   $validator->allowEmpty($formFieldCurrent, false);

**Comment by dereuromark** [comment]
What version are you using? I just fixed it for 3.4+, please upgrade if you are using that CakePHP version.

**Comment by dereuromark** [comment]
I updated my sandbox with the new version, the demo is now working again as expected: http://sandbox.dereuromark.de/sandbox/tools-examples/password-edit

**Comment by dereuromark** [comment]
Does the new version work out?

**Comment by blieb** [comment]
I've upgraded to version 1.3.0 but I'm still able to change password on edit form with leaving the pwd_current empty.

**Comment by dereuromark** [comment]
OK, I will check again. If you have any PR with a fix that would be great.

**Comment by blieb** [comment]
The fix 1 mentioned in first post works perfect. But I don't know if it is the behaviour you want. When you change that, It will always require the current password. even when there is no new password.

**Comment by dereuromark** [comment]
I think this is the proper fix:
```
-			$validator->allowEmpty($formFieldCurrent, !$this->_config['require']);
+			$require = $this->_config['require'];
+			$validator->allowEmpty($formFieldCurrent, function ($context) use ($require, $formField) {
+				if (!$require && !empty($context['data'][$formField])) {
+					return false;
+				}
+				return !$require;
+			});
```

**Comment by blieb** [comment]
Tested it, that works perfect. but is it maybe possible to also add a feature that it also require current password by updating some other fields? (like email) Maybe just a setting "alwaysRequireCurrent" or "requireCurrentForFields" ? :)

or maybe create a validation provider which contains the code for validating the current password

**Comment by dereuromark** [comment]
Here is the commit: https://github.com/dereuromark/cakephp-tools/commit/5e535b8d265a88e68fa42d7932b16bc3da119529
I can soon tag a new patch release.

So you want to use it for some other purpose? ;)
I think you can already do that by getting the validator prior to saving:

    $validator = $this->ModelName->validator(...)
    // Modify/add rules

This way you can attach the require on different or all fields etc.

**Comment by dereuromark** [comment]
Patch is released, and I added an example here in the sandbox:
http://sandbox.dereuromark.de/sandbox/tools-examples/password-edit-current
