### ISSUE TITLE
Wouldn't it be usefulu that trimDeep could ignore non-string values

### ISSUE THREAD

**Issue by berarma** [dereuromark/cakephp-tools#181]
Hi @dereuromark.

We talked friday about the CommonComponent converting null to empty string. I've seen you've fixed it already. Thanks.

At the time I was thinking about adding an argument to trimDeep to tell it not to cast non-string values. I thought about it this way because I didn't like the idea of this component doing something else besides strictly trimming strings. Anyway, since we're talking about request data I guess the only possible values will always be null and strings. But, wouldn't this be useful as a feature of the ```trimDeep``` function?

PHP documentation hints the first argument of ```trim``` as a string and doesn't define what it will do with other types. You could consider having a PHP-compatible trim operation mode and a more strict mode that ignores non-strings.

**Comment by dereuromark** [comment]
Feel free to PR any further additions, but I guess your point is correct: Usually those kind of POST data can only be strings, and that's what it should be used for. The null part was already an exception, e.g. reading from API data input.

Also: No one is forced to use the plugin methods, one can always use a project specific component hook with a more project-fitting trimming functionality.

**Comment by berarma** [comment]
I'm always a bit unsure about where the line between fork/go-your-own-way/contribute is. Your work is always helpful anyways. I'll try the new version and see how the real needs evolve.

Thanks!
