### ISSUE TITLE
Using a translated field as "field" in SluggedBehavior

### ISSUE THREAD

**Issue by lorro** [dereuromark/cakephp-tools#183]
Hi Mark,

I'm wondering if this is possible. We have a CategoriesTable with the following translated fields.
```php
$this->addBehavior('Translate', [
   'fields' => ['name', 'description', 'slug'],
]);
```

Now, we would like to make a translated slug based on the name field. 

```php
$this->addBehavior('Tools.Slugged', [
          'label' => 'name',
          'field' => 'slug',
          'mode' => 'ascii',
          'overwrite' => true,
          'unique' => true,
          'case' => 'low'
        ]);
```

But then we get the following error (not surprisingly)
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Categories.slug' in 'where clause'

Is there a way we can make this work or is this still a work in progress?
I see in the code there's a _multiSlug method, but apparently it's never called.

Also we would like this slug to be "hierarchical", we used the cakephp TreeBehavior for that?
But I can't seem to find any documentation whether this is actually possible to do :)

Thanks!

**Comment by dereuromark** [comment]
The multi slug is somewhat 2.x related that has not been ported.
Also, your translation and hierarchical features so far are not inside the scope of it afaik.
If you see a way how to make it possible, please make a PR we can work on and discuss.
Maybe it is an easy extension to add as a minor.

**Comment by dereuromark** [comment]
field could also be a closure to read from a different field in the given entity, or, if there is a join just set ModelName.fieldName then instead.
