### ISSUE TITLE
Cannot convert value to string

### ISSUE THREAD

**Issue by jojomartius** [dereuromark/cakephp-tools#190]
In some scenarios i dont understand i got an exception when i save my Model:

Exception: Cannot convert value to string in [/xxxx/vendor/cakephp/cakephp/src/Database/Type/StringType.php, line 52]

Havn't really figured out what that caused, but i think it had to do in most cases with nested models AND in a lot of cases inside unit tests.

**Comment by dereuromark** [comment]
Did you debug it, what is the value here trying to be converted?

**Comment by jojomartius** [comment]
array(1) {
  [0]=>
  string(2) "20"
}

**Comment by dereuromark** [comment]
Find out why there is an array.
I dont think it is the plugins fault here.

**Comment by jojomartius** [comment]
Maybe i misused your plugin, but i thought the idea is that the intention is that the model converts everything what is in a field mentioned in $this->addBehavior('Tools.Jsonable', ['fields' => [...]]); from json into arrays and if i save again from array to a json string?

**Comment by dereuromark** [comment]
Yeah, see the test cases.
