### ISSUE TITLE
Update pelago/emogrifier dependency to ^2.0.0

### ISSUE THREAD

**Issue by oliverklee** [dereuromark/cakephp-tools#199]
Emogrifier 2.0.0 has been released, fixing a lot of bugs. If the new PHP >= 5.5 requirement is not a problem, the dependency should be updated to ^2.0.0.

**Comment by dereuromark** [comment]
A PR would be welcome.

**Comment by oliverklee** [comment]
Will do.

**Comment by oliverklee** [comment]
I think I created this ticket for the wrong package (as this package does not depend on `pelago/emogrifier`). Sorry for the confusion. Closing.
