### ISSUE TITLE
CakePHP 3.6/4.0 way for trimming inputs?

### ISSUE THREAD

**Issue by MCF** [dereuromark/cakephp-tools#206]
In CakePHP 3.6 user `request->data = ...` is deprecated and going away in 4.0.  I like your solution for trimming all inputs at the request level as shown in your CommonComponent:

https://github.com/dereuromark/cakephp-tools/blob/8b8e902d6781cb3685a79685fc415f9fdb038c4a/src/Controller/Component/CommonComponent.php#L30

Do you have any suggestions for a version 3.6/4.0 friendly way of doing the same sort of thing?

Some others seem concerned that cleaning the request data is [a bad thing](https://discourse.cakephp.org/t/cakephp-3-4-how-to-change-request-data-programmaticly/2120) but I personally don't think it is that big of a deal.  Still we have to play nicely with the newer versions of the framework...

Any thoughts or suggestions would be appreciated.

**Comment by dereuromark** [comment]
Indeed, this is no big deal. And it is better in the component than any middleware, as the middleware is harder to customize, if some controllers need it.
`$request = $request->withData(...)` should work.
If that is 3.5 compatible, you can do a PR here.

**Comment by MCF** [comment]
According to the comments in the code `withData(...)` has been around since 3.4.

I'll try to fit in a pull request in the next few days.

**Comment by inoas** [comment]
Can routing and middleware play together already? If they can:
https://gist.github.com/inoas/a835c412c55bc0a2cf689e595c357167

**Comment by dereuromark** [comment]
I am not a big fan of blowing up routing for this. The controllers should maybe exclude their requests from this if needed. But for people that really want this globally, the middleware approach could also be an option, of course.

**Comment by challgren** [comment]
Posted Data wasn't completed yet in #220. So this should remain open still.
