### ISSUE TITLE
Slugged include character not recommended

### ISSUE THREAD

**Issue by sandra88vr** [dereuromark/cakephp-tools#207]
Hi Mark!

Using Slugged Behavior I have seen that with the `url` mode, `comma` character is omitted, then, slugs with comma is generated, not recommended by SEO. I could configure it from my call to the behavior, but I think it is appropriate to comment on it if you think it is convenient to modify it.

PD: Excuse my English :)

Thanks!!

Sandra

**Comment by dereuromark** [comment]
Do you want to make a PR to fix this?
We can also deprecate that one, and instead use a more recommended strategy.
