### ISSUE TITLE
SMTP Error: 501 5.1.3 Bad recipient address syntax on empty Config.adminEmail 

### ISSUE THREAD

**Issue by asgraf** [dereuromark/cakephp-tools#230]
Currently there is a feature that prevents sending email when debugging is enabled.
https://github.com/dereuromark/cakephp-tools/blob/master/src/Mailer/Email.php#L559

Please make this feature optional.

When `Config.adminEmail` is not set `SMTP Error: 501 5.1.3 Bad recipient address syntax` error is generated for every email send attempt.

**Comment by dereuromark** [comment]
As you can clearly see from the code, as well as docs, this is optional and needs production mode (Configure Config.live true) set.

    if (Configure::read('debug') && Configure::read('Config.live')) {}

Is there anything else that is needed?
