### ISSUE TITLE
cakephp 3.x BitmaskedBehavior validation

### ISSUE THREAD

**Issue by pavel-dovgoshiya** [dereuromark/cakephp-tools#234]
It seems validation bug in behavior. I have create in table next code:
Added to initialize function
$this->addBehavior('Bitmasked', ['mappedField' => 'severities', 'field' => 'severity']);

then when i create validation rule for field name severities then its not in entity data, its seems start work when i did outcomment next:
297: unset($data[$mappedField]); in function encodeBitmaskDataRaw
After that this field data come in entity for make validation.

In view template i have code:
<?= $this->Form->control('severities', ['options'=>$Entity->severities(), 'multiple'=>'checkbox']); ?>

Thanks

**Comment by dereuromark** [comment]
Thank you for reporting this.
Are you able to provide a PR with the fix? Then I can see if I can look into it and provide additional test cases etc.

**Comment by pavel-dovgoshiya** [comment]
I just did out comment one line:

public function encodeBitmaskDataRaw(ArrayObject $data) {
$field = $this->_config['field'];
if (!($mappedField = $this->_config['mappedField'])) {
$mappedField = $field;
}
$default = $this->_getDefault($field);

if (!isset($data[$mappedField])) {
return;
}

$data[$field] = $this->encodeBitmask($data[$mappedField], $default);
if ($field !== $mappedField) {
- unset($data[$mappedField]);
+ //unset($data[$mappedField]);
}
}

ср, 13 мар. 2019 г. в 12:04, Mark Sch. <notifications@github.com>:

**Comment by dereuromark** [comment]
Please make a PR here so we can see if the tests pass or fail.

**Comment by dereuromark** [comment]
One question: Why dont you write a validation for the un-mapped (internal) field?
In this case `severity` would be what the behavior expects validation to be run on.

**Comment by pavel-dovgoshiya** [comment]
I agree, but in form its other name then its make sence to validate this
field. And this field from form validate in other way then this converted
field.

public function validationDefault(Validator $Validator) {
   $Validator->requirePresence($field='severities')
      ->allowEmptyArray($field, false)
      ->add($field, 'custom', [
         'rule' => function ($values, $context) {
         foreach ($values as $value)
               if (!Trial::severities($value))
                  return false;
            return true;
         },
      ])
      ;
   return $Validator;
}

P.S. still in process to make PR.

ср, 13 мар. 2019 г. в 12:51, Mark Sch. <notifications@github.com>:

**Comment by dereuromark** [comment]
OK - If nothing breaks I am fine with not unsetting the field :)
