### ISSUE TITLE
The name 'key' is a MySQL reserved keyword.

### ISSUE THREAD

**Issue by saeideng** [dereuromark/cakephp-tools#236]
The name 'key' is a MySQL reserved keyword.
```
INSERT INTO tokens (
  user_id, type, key, content
) 
VALUES 
  (
    '1', '....', '....', 
    ''
  )
```
```
Error: SQLSTATE[42000]: Syntax error or access violation: 
1064 You have an error in your SQL syntax; check the manual that corresponds to
 your MySQL server version for the right syntax to use near 'key, content) VALUES ('1', '...', '...' at line 1 
```

code
https://github.com/dereuromark/cakephp-tools/blob/4f720ea4a0e3454cff5f5240c8e59cc267ec3fb6/src/Model/Table/TokensTable.php#L102-L107

**Comment by dereuromark** [comment]
I use identifier escaping by default.

**Comment by saeideng** [comment]
:+1:  for  rename in the next major

**Comment by dereuromark** [comment]
A PR with migration is welcome for cake4 branch now.

**Comment by dereuromark** [comment]
Unfortunately, now is a bit late. Stable is released.

**Comment by dereuromark** [comment]
Actually, given that this wasnt documented yet, maybe we can do https://github.com/dereuromark/cakephp-tools/pull/259 as minor now.
