### ISSUE TITLE
SluggedBehavior does not work with virtual fields

### ISSUE THREAD

**Issue by asgraf** [dereuromark/cakephp-tools#250]
I have virtual field `name` defined in in my `Userpackage` entity and `_getName()` getter has been implemented.

```PHP
//in my /Model/Entity/Userpackage.php
protected $_virtual = [
        'name',
    ];
```

```PHP
//in my /Model/Entity/Userpackage.php
 protected function _getName()
    {
        if ($this->custom_name) {
            return $this->custom_name;
        }
        if (!$this->package) {
            throw new InternalErrorException('Invalid Package');
        }
        return $this->package->name;
    }
```
```PHP
//in my /Model/Table/UserpackagesTable.php
$this->addBehavior('Tools.Slugged', [
            'label' => 'name',
            'case' => 'low',
            'mode' => [Text::class, 'slug'],
            'unique' => false,
            'overwrite' => true
        ]);
```
Now i get following error:
```
(SluggedBehavior::setup) model Userpackages is missing the field name specified in the setup.
```

**Comment by dereuromark** [comment]
The behavior is only for DB fetching and real fields.
What you want you can easily do inside your _getName() method directly.
Just return the Text::slug() value there. No need for any behaviors.

**Comment by asgraf** [comment]
You seem to not understand my code correctly.
I have real field `slug` in my userpackages table.
I want to fill this real field `slug` with a string generated from slugging contents of virtual field `name`

**Comment by asgraf** [comment]
You seem to not understand my code correctly.
I have real field `slug` in my userpackages table and i want to be able to to serach by slug.
So i want to fill this real field `slug` with a string generated from slugging contents of virtual field `name`

**Comment by dereuromark** [comment]
I sure don't quite fully understand the use case here.
Feel free to provide a patch if you think something could be improved or fixed here.

As for non-real fields support, you could also try to extend/overwrite
```php
public function hasField($field)
{
    if ($field === 'fake') { return true; }

    return parent::hasField($field);
}
```

Just an idea.

**Comment by asgraf** [comment]
Following code seems to solve the problem:
```PHP
public function hasField($field)
    {
        $virtualFields = $this->newEntity()->getVirtual();
        if(in_array($field, $virtualFields)) {
            return true;
        }

        return parent::hasField($field);
    }
```
But i still think that slug behavior should work correctly out of the box without need of overriding native cakephp methods

**Comment by dereuromark** [comment]
Can u maybe add a pr to Support this?
Either by making check optional or including virtual fields?

**Comment by dereuromark** [comment]
My idea:

    'checkExistence' => false

for your case to not check if the field exists in model.

**Comment by dereuromark** [comment]
Actually, the existence check is mainly done to be able to get some meta data.
But it has a fallback in place, and also a passing test case:

testSlugGenerationWithVirtualField()

Can you please check why this test case with a virtual field does work, but your example doesnt?

**Comment by dereuromark** [comment]
Please use latest master to check
I added a better debug message for the error: https://github.com/dereuromark/cakephp-tools/commit/cde92a50ba30702c6c5d8cdd3769641d0873065a

**Comment by dereuromark** [comment]
Any update here?
