### ISSUE TITLE
Feature Request: Add new class to log data into custom files

### ISSUE THREAD

**Issue by ishan-biztech** [dereuromark/cakephp-tools#260]
Add convenience class method to log data directly into custom files.

So instead of doing this:

```php
use Cake\Log\Log;

Log::config('custom_file', [
    'className' => 'File',
    'path' => LOGS,
    'levels' => ['debug'],
    'file' => 'custom_file.log',
]);

Log::write('debug', 'Data to log into file goes here');
```

With this approach, we have multiple issues:
- Duplicate log data into `$level.log` file and `custom_file.log`
- When we have to write more logs into same file from different parts of the project, we have to copy-paste this code every time.

I think we should have simple API here as below:

```php
use Tools\Log\Log;

Log::write('Data to log into file', 'custom_file');
```

Here we can overcome the issue of duplicating records, also we have reduced code too.

@dereuromark Please let me know your thoughts on this. If you think it's good idea to have this feature in this plugin, I can create a PR to add this thing.

**Comment by dereuromark** [comment]
I had the same issues in the past, but I came to accept and use those config() calls in bootstrap for all kind of custom configs. For many I use "scope" functionality.

But I am also fine with a custom Tools logger.
If you want to make a PR, feel free.
