### ISSUE TITLE
[InvalidArgumentException] Min/Max overflow for value `25` (0...1)

### ISSUE THREAD

**Issue by SparkyRih** [dereuromark/cakephp-tools#264]
I'm on CakePHP 3.9, and use the latest verions of this library for this version of CakePHP...

When trying to go to the cakephp-queue pages I get the following error:

[InvalidArgumentException] Min/Max overflow for value `25` (0...1) (/var/www/html/vendor/dereuromark/cakephp-tools/src/View/Helper/ProgressHelper.php:113) #0 /var/www/html/vendor/dereuromark/cakephp-tools/src/View/Helper/ProgressHelper.php(94): Tools\View\Helper\ProgressHelper->draw(25, 18) #1 /var/www/html/vendor/dereuromark/cakephp-queue/src/View/Helper/QueueProgressHelper.php(77): Tools\View\Helper\ProgressHelper->progressBar(25, 18) #2 /var/www/html/src/Template/Plugin/Queue/Admin/Queue/index.ctp(89): Queue\View\Helper\QueueProgressHelper->progressBar(Object(Queue\Model\Entity\QueuedJob), 18) #3 /var/www/html/vendor/cakephp/cakephp/src/View/View.php(1435): include('/var/www/html/s...') #4 /var/www/html/vendor/cakephp/cakephp/src/View/View.php(1393): Cake\View\View->_evaluate('/var/www/html/s...', Array) #5 /var/www/html/vendor/cakephp/cakephp/src/View/View.php(892): Cake\View\View->_render('/var/www/html/s...') #6 /var/www/html/vendor/cakephp/cakephp/src/Controller/Controller.php(791): Cake\View\View->render(NULL, NULL) #7 /var/www/html/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(126): Cake\Controller\Controller->render() #8 /var/www/html/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(94): Cake\Http\ActionDispatcher->_invoke(Object(Queue\Controller\Admin\QueueController)) #9 /var/www/html/vendor/cakephp/cakephp/src/Http/BaseApplication.php(256): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #10 /var/www/html/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #11 /var/www/html/vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php(126): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #12 /var/www/html/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #13 /var/www/html/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(164): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #14 /var/www/html/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #15 /var/www/html/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #16 /var/www/html/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #17 /var/www/html/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(100): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #18 /var/www/html/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #19 /var/www/html/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #20 /var/www/html/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #21 /var/www/html/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #22 /var/www/html/vendor/cakephp/cakephp/src/Http/Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #23 /var/www/html/webroot/index.php(40): Cake\Http\Server->run() #24 {main} Request URL: /admin/queue Referer URL: http://192.168.208.128:8080/admin

**Comment by dereuromark** [comment]
25 should be 0.25 as the error message Shows.
How are you using it inside queue?
Looks like a User error to me.

**Comment by SparkyRih** [comment]
Sorry you're right, I didn't read the params: "@param float $progress Value from 0 to 1".
