### ISSUE TITLE
Cake\I18n\Time is deprecated

### ISSUE THREAD

**Issue by LordSimal** [dereuromark/cakephp-tools#272]
Opening the QueuedJobs overview of the dereuromark/cakephp-queue plugin shows a deprecation warning (but not really telling)

```
CAKE/Core/functions.php:322
The `Time` class has been deprecated. Use the immutable alternative `FrozenTime` instead - <my-project>/vendor/cakephp/cakephp/src/I18n/Time.php, line: 134 
You can disable all deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED`, 
or add `vendor/cakephp/cakephp/src/I18n/Time.php` to `Error.ignoredDeprecationPaths` in your `config/app.php` 
to mute deprecations from only this file.
```

But CAKE/Core/functions.php:322 is only the `deprecationWarning()` function in core.
Setting a xdebug breakpoint and looking at the stacktrace I found out that https://github.com/dereuromark/cakephp-tools/blob/master/src/Utility/Time.php#L10 uses the now deprecated Time class.

I will create a PR to change that to FrozenTime.

**Comment by LordSimal** [comment]
Ah wait there is actually a deprecated tag in that class already. So the fix should actually happen in the dereuromark/cakephp-queue plugin.

**Comment by dereuromark** [comment]
which happened in https://github.com/dereuromark/cakephp-queue/commit/fc7c83f152ed60db50f2a69698c6a6cbb8fa5915#diff-f7abae7d1436ee28fe695b4ed4d9e7379254448cc230f5eb85cfb8c4488e97fcR14

**Comment by LordSimal** [comment]
See https://github.com/dereuromark/cakephp-queue/pull/310 for the actual reason of that deprecation message
