### ISSUE TITLE
CakePHP 4.5 deprecations

### ISSUE THREAD

**Issue by LordSimal** [dereuromark/cakephp-tools#287]
The `engine` option for TextHelper will be removed in 5.0 in `src/View/Helper/TextHelper.php, line: 45`

**Comment by dereuromark** [comment]
Jep, it directly uses 
```php
	public function __call(string $method, array $params): mixed {
		return \Tools\Utility\Text::{$method}(...$params);
	}
```
I wonder if we should shim the engine for Tools "Text" and "Number" here, to allow also easier customization here if needed.

The same is currently done for Time helper where engine is still active.

**Comment by dereuromark** [comment]
We probably want to backport https://github.com/dereuromark/cakephp-tools/commit/2500c941596e4cf48337c9e0467d7db8d9e17011 into the constructors, overriding core here, allowing the deprecation not to be triggered.

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-tools/releases/tag/2.6.0
