### ISSUE TITLE
Revision Behavior interferes with validation error messages

### ISSUE THREAD

**Issue by dyske** [dereuromark/cakephp-tools#29]
I'm not sure if you are aware of this:

http://stackoverflow.com/questions/8949538/cakephp-revision-behavior-hurdles-validation-error

On that thread, nobody figured out why this is happening. Today, I spent many hours troubleshooting this, and I figured out why this is happening.

In Cake's Controller->render() [line 937], there is a loop that iterates through an array of classes that have been registered into ClassRegistry. This loop uses object aliases as the keys for the validationErrors array. Like this:

$this->View->validationErrors[$currentObject->alias]

When you get a list of revisions by calling revisions() method, RevisionBehavior registers a duplicate of your model. So, if your model is "Post", RevisionBehavior ends up registering another one called "Post" when it instantiates the shadow Model at line 973. The actual error message is stored under the first instance, but this gets overwritten when Cake loops one more time. This is why the error message disappears.

So, to get around this, this is the line I added immediately after RevisionBehavior instantiates a shadow model. At line 975:

ClassRegistry::removeObject(Inflector::singularize($fullTableName));

This would de-register (remove) the shadow class from the registry, and the conflict with the validation errors would be resolved.

**Comment by dereuromark** [comment]
Revision is deprecated and only 2.x needs fixing if someone is filling to provide a PR.

**Comment by dereuromark** [comment]
Closing until PR is open.
