### ISSUE TITLE
SoftDelete interferes with Logable/Revision-Behaviour

### ISSUE THREAD

**Issue by LDSign** [dereuromark/cakephp-tools#4]
Hi Mark

Today I've started to use your toolbox for Cake. Nice work! :)

One thing Ive noticed is, that the SoftDelete brings some errors in combination with the Revision and Logable-Behaviour when deleting an item. It seems all db-entries are correctly set, but Cake give me some errors:

Notice (8): Undefined index: Company [APP\Plugin\Tools\Model\Behavior\RevisionBehavior.php, line 835]

Warning (2): Invalid argument supplied for foreach() [APP\Plugin\Tools\Model\Behavior\RevisionBehavior.php, line 835]

Notice (8): Undefined index: Company [APP\Plugin\Tools\Model\Behavior\LogableBehavior.php, line 503]

Company is the related model. The order in actsAs is as "'Tools.SoftDelete','Tools.Revision','Tools.Logable','Tools.WhoDidIt'".

What Ive done wrong? Could you give me a hint please?

By the way: Is there any complete documentation for the toolbox?

Thanks for your help,
Frank

P.S. - Du kannst auch gerne in deutsch antworten ;)

**Comment by dereuromark** [comment]
SoftDelete is deprecated and only 2.x needs fixing if someone is filling to provide a PR.

**Comment by dereuromark** [comment]
Closing until PR is open.
