### ISSUE TITLE
SoftDelete interferes with Logable/Revision-Behaviour Again

### ISSUE THREAD

**Issue by josephzidell** [dereuromark/cakephp-tools#8]
Mark,
As mentioned in issue #4, I have the following ```$actsAs``` in a "Story" model:
```php
public $actsAs = array(
	'Tools.Revision' => array(
		'ignore' => array( 'updated', 'comment_count', 'order', 'task_count' )
	),
	'Tools.Logable' => array(
		'change' => 'full',
	),
	'Tools.SoftDelete',
);
```
and a ```delete``` action in the ```StoriesController```:
```php
public function admin_delete($id = null) {
	$this->Story->id = $id;
	if (!$this->Story->exists()) {
		throw new NotFoundException(__('Invalid story'));
	}

	$story = $this->Story->read(); // needed for slugs for redirect arrays

	if ($this->Story->delete()) {
		$this->Session->setFlash(__('Story deleted'));
		$this->redirect(array( 'controller' => 'projects', 'action' => 'view', 'project_slug' => $story['Project']['slug']));
	} else {
		$this->Session->setFlash(__('Story was not deleted'));
		$this->redirect(array( 'action' => 'view', 'project_slug' => $story['Project']['slug'], 'story_slug' => $story['Story']['slug'] ));
	}
}
```
After hitting "delete", it redirects to the "story page" (else branch), and the flash message says "Story was not deleted", but the browser says "Cannot find story".

In addition, the log table records an "edit" in the action field, with the "change" field recording ```deleted () => (1), deleted_date () => (2013...), updated (2013...) => (2013...)```

Any ideas?
Thanks

**Comment by dereuromark** [comment]
SoftDelete is deprecated and only 2.x needs fixing if someone is filling to provide a PR.

**Comment by dereuromark** [comment]
Closing until PR is open.
